language: c

git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib
      - g++-4.8
      - texlive
      - texinfo
      - valgrind
  coverity_scan:
    project:
      name: $TRAVIS_REPO_SLUG
      description: MATLAB MAT File I/O Library
    notification_email: $COVERITY_SCAN_EMAIL
    build_command: make
    branch_pattern: coverity_scan

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "C2T0NCiqo98RZXaBTqSWpxcpKhAryOD9VcZ02keuyOPCeNpaLKeo36R/8iAhHWvQddU3V9x0H8EHGN4QY78I1kH3OTwTsGueyRTjKvBsrWlR88pO0CJ33MXz9IvpVE32zACKt2Ltj2GBIUzl0Nm6uwjJXW59pL/86X9ShHK/+hs8Trqu3Zm8MiWg0z79xZzHo+9m7RXW0i5jwxBfIbW15GIMc1TMZC31eHBDjQRCTL89IZzJXVf1ZCd+OsUpvuOVneAl9ihvqyZ3fkK/8n7iVr3TzJDIpj4I3AgVSdg6D0vNsW5HE/czZKTHs6yVI/ImcpPnyApd85MKxjkyppDi3WTBvWn4MkPDMxj1ZJzDQ+0tGIcfaQn9uXiwZCIIezodFK5aY8/OoK9/cVRfjHjZrXkv+hfH0Xys9DrlhSKpeusU0hAS2yoz10g+aN/Sz4fGeRlGrvU0HIncFdXLsD30v7LDTZn4dBIH7C+xE6pbcQ7Y3bGEC3CyR0UbFCbjY20JPMa0k7FBmLRpBUHn9mxJ/eJSnWH/ZI4YRWyJd5fAQvUPvY+5oP+IaEo0oZgSelEUnEssmySFFrVN4YC1GJb63AT7tLPnhgghmzSZUMG/l7Zj0++TEQv+OhtVg8E57iSV0l7WXXwapCyjbFHvjPEwvgZ3plc9XOo+HqYxeHtkx40="
    # COVERITY_SCAN_EMAIL
    - secure: "Qux4CPWkAXdpWPbUwqKTtimTU/xKC2oLtqzH5oMYuTUqyAX9D6XAEx+lq5ADNk5UAQuq4kCWYxPyNOu85vZPV/9INBZ9sSJ+Y5cbQLpJ6nqY7nQHuL5WoIHDtyabgo3mKlsY4mkpM0qcHgHib98/j7vG573pBfp4ihcUu5eKUNxlP07nUILeBPpuJz5GWoCzikU9M0tgjwmydWoa+dJ726HPoPjsu2VY1RFov63u+BWX/c3FUTWyleGVIsQbQeQUcIjMMtHyv0r3wqdsryk88m1rEpDrAy60fki71lcfGuxhzgkSMLezFu2Qj8EqtUrC+Xh4/VIFdn3XbR527OrTQrkJYDelZvEQSoEd3NgiWu5A0R+Zr68YJLjPHoW4TJFj0AG7Nek9bBr27CJOMjAzBVp8FMcVl3/6ApfJb0R89vslPA0J+p/UJdmjhuriiigojMwJQwESpRLtp+oietfr2UtQUeMc9AqCZf4jRzNK4ooEC75Z9MM2FFiuDLhAyYsCwwHrHilXHCCStdjs1jk7YV1+AyU5HIokAYPXjWwxT5BWSIc5wfnIj4lGdMhzJien8/qjyU6kQPiikorKTgd2eD6KzQULuccPudnN9lK6eT+DY4LZ3rfSMGFkMA72w0nmEK4sTGuT8zMC9KS0hgat5b8mzSJ3xhaXig3gQXkrYZk="

matrix:
  include:
    - os: osx
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION_DIR=hdf5_1_8_17
    - os: osx
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION_DIR=hdf5_1_8_17

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]]; then pip install --upgrade pip; pip install --user cpp-coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall libtool && brew install libtool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc48; fi

install:
  - if [[ "$HDF5_VERSION_DIR" == "hdf5_1_8_17" ]]; then ./.install_hdf5_1_8.sh; fi
  - if [[ "$HDF5_VERSION_DIR" == "hdf5_1_10_0" ]]; then ./.install_hdf5_1_10.sh; fi
  - cd $TRAVIS_BUILD_DIR
  - mkdir MSL
  - cd MSL
  - git init
  - git remote add -f origin https://github.com/svn2github/Modelica_StandardLibrary
  - git config core.sparseCheckout true
  - echo "Modelica/Resources/Data/Tables/" >> .git/info/sparse-checkout
  - git pull origin master
  - cd $TRAVIS_BUILD_DIR

before_script:
  - ./autogen.sh
  - ./configure --quiet --enable-shared --enable-coverage --enable-debug --enable-mat73=$ENABLE_MAT73 --enable-extended-sparse=$ENABLE_EXTENDED_SPARSE --with-zlib=$WITH_ZLIB --with-pic --with-hdf5=$TRAVIS_BUILD_DIR/$HDF5_VERSION_DIR/hdf5

script:
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then make; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then travis_wait 30 make check; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./test/test_snprintf; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./test/test_mat -H; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./test/test_mat -L; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./test/test_mat -V; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./tools/matdump -v -H; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./tools/matdump -V; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./tools/matdump -d ./MSL/Modelica/Resources/Data/Tables/test_v6.mat s; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]] && [[ "$WITH_ZLIB" == "yes" ]]; then ./tools/matdump -d ./MSL/Modelica/Resources/Data/Tables/test_v7.mat s; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]] && [[ "$ENABLE_MAT73" == "yes" ]]; then ./tools/matdump -d ./MSL/Modelica/Resources/Data/Tables/test_v7.3.mat s; fi

after_success:
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]]; then coveralls -e coverity_model.c -e getopt -e test/datasets/matio_test_cases.m -e test/mat2hdf.c -e share -e patches -e $HDF5_VERSION_DIR -e visual_studio --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp'; fi
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make pdf; fi

notifications:
  email: false

sudo: required
